# Generated by Django 3.1.7 on 2021-08-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_twitteruser_type_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_info',
            field=models.JSONField(null=True),
        ),
    ]
